# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.1

# Default target executed when no arguments are given to make.
default_target: all
.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:
.PHONY : .NOTPARALLEL

#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:

# Remove some rules from gmake that .SUFFIXES does not remove.
SUFFIXES =

.SUFFIXES: .hpux_make_needs_suffix_list

# Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:
.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/local/Cellar/cmake/3.1.3/bin/cmake

# The command to remove a file.
RM = /usr/local/Cellar/cmake/3.1.3/bin/cmake -E remove -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /Users/steffenschmidt/Desktop/LauzHack/LauzHack2016

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /Users/steffenschmidt/Desktop/LauzHack/LauzHack2016

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake cache editor..."
	/usr/local/Cellar/cmake/3.1.3/bin/ccmake -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache
.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/local/Cellar/cmake/3.1.3/bin/cmake -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache
.PHONY : rebuild_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /Users/steffenschmidt/Desktop/LauzHack/LauzHack2016/CMakeFiles /Users/steffenschmidt/Desktop/LauzHack/LauzHack2016/CMakeFiles/progress.marks
	$(MAKE) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /Users/steffenschmidt/Desktop/LauzHack/LauzHack2016/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean
.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named main

# Build rule for target.
main: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 main
.PHONY : main

# fast build rule for target.
main/fast:
	$(MAKE) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/build
.PHONY : main/fast

src/calibrate.o: src/calibrate.cpp.o
.PHONY : src/calibrate.o

# target to build an object file
src/calibrate.cpp.o:
	$(MAKE) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/src/calibrate.cpp.o
.PHONY : src/calibrate.cpp.o

src/calibrate.i: src/calibrate.cpp.i
.PHONY : src/calibrate.i

# target to preprocess a source file
src/calibrate.cpp.i:
	$(MAKE) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/src/calibrate.cpp.i
.PHONY : src/calibrate.cpp.i

src/calibrate.s: src/calibrate.cpp.s
.PHONY : src/calibrate.s

# target to generate assembly for a file
src/calibrate.cpp.s:
	$(MAKE) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/src/calibrate.cpp.s
.PHONY : src/calibrate.cpp.s

src/calibrateColors.o: src/calibrateColors.cpp.o
.PHONY : src/calibrateColors.o

# target to build an object file
src/calibrateColors.cpp.o:
	$(MAKE) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/src/calibrateColors.cpp.o
.PHONY : src/calibrateColors.cpp.o

src/calibrateColors.i: src/calibrateColors.cpp.i
.PHONY : src/calibrateColors.i

# target to preprocess a source file
src/calibrateColors.cpp.i:
	$(MAKE) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/src/calibrateColors.cpp.i
.PHONY : src/calibrateColors.cpp.i

src/calibrateColors.s: src/calibrateColors.cpp.s
.PHONY : src/calibrateColors.s

# target to generate assembly for a file
src/calibrateColors.cpp.s:
	$(MAKE) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/src/calibrateColors.cpp.s
.PHONY : src/calibrateColors.cpp.s

src/keyboard/Flasher.o: src/keyboard/Flasher.cpp.o
.PHONY : src/keyboard/Flasher.o

# target to build an object file
src/keyboard/Flasher.cpp.o:
	$(MAKE) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/src/keyboard/Flasher.cpp.o
.PHONY : src/keyboard/Flasher.cpp.o

src/keyboard/Flasher.i: src/keyboard/Flasher.cpp.i
.PHONY : src/keyboard/Flasher.i

# target to preprocess a source file
src/keyboard/Flasher.cpp.i:
	$(MAKE) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/src/keyboard/Flasher.cpp.i
.PHONY : src/keyboard/Flasher.cpp.i

src/keyboard/Flasher.s: src/keyboard/Flasher.cpp.s
.PHONY : src/keyboard/Flasher.s

# target to generate assembly for a file
src/keyboard/Flasher.cpp.s:
	$(MAKE) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/src/keyboard/Flasher.cpp.s
.PHONY : src/keyboard/Flasher.cpp.s

src/main.o: src/main.cpp.o
.PHONY : src/main.o

# target to build an object file
src/main.cpp.o:
	$(MAKE) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/src/main.cpp.o
.PHONY : src/main.cpp.o

src/main.i: src/main.cpp.i
.PHONY : src/main.i

# target to preprocess a source file
src/main.cpp.i:
	$(MAKE) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/src/main.cpp.i
.PHONY : src/main.cpp.i

src/main.s: src/main.cpp.s
.PHONY : src/main.s

# target to generate assembly for a file
src/main.cpp.s:
	$(MAKE) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/src/main.cpp.s
.PHONY : src/main.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... rebuild_cache"
	@echo "... main"
	@echo "... src/calibrate.o"
	@echo "... src/calibrate.i"
	@echo "... src/calibrate.s"
	@echo "... src/calibrateColors.o"
	@echo "... src/calibrateColors.i"
	@echo "... src/calibrateColors.s"
	@echo "... src/keyboard/Flasher.o"
	@echo "... src/keyboard/Flasher.i"
	@echo "... src/keyboard/Flasher.s"
	@echo "... src/main.o"
	@echo "... src/main.i"
	@echo "... src/main.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

